### ISSUE TITLE
Tune up resources for data warehouse namespace

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-data-warehouse#17]
The minimal resources we currently have in our namespace will not be enough. Tune these up as needed.

**Comment by mikevespi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-data-warehouse/17?planning-poker) with Zenhub @dleard
