### ISSUE TITLE
Create a cronjob that pulls data from a source database

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-data-warehouse#21]
We will need a cronjob to pull data from the source database. This cronjob should use pg_dump to pull the correct schema(s) from the source into a <source>_load schema in the data warehouse database.

Note: we may want to use the --no-acl flag so that we don't pull roles unnecessarily into the warehouse.

AC:
- [ ] A "pull from source" cronjob exists in the data warehouse namespace
- [ ] The cronjob pg_dumps the source and pg_restores into a _load schema
- [ ] The cronjob applies any necessary grants (ie: to a read-only user) on the _load schema
- [ ] The cronjob drops the live schema and renames _load to be the live schema

**Comment by mikevespi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-data-warehouse/21?planning-poker) with Zenhub @dleard

**Comment by patriciarussellCAS** [comment]
@mikevespi & @dleard I'm not sure if this is complete and if it's still being blocked #24?

**Comment by dleard** [comment]
This is done
