### ISSUE TITLE
Connect the warehouse database to metabase

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-data-warehouse#22]
Metabase should connect to the warehouse database using a readonly user.
Connect metabase to the data warehouse database using that user (and perhaps a service account should be created in openshift to do this?)

**Comment by mikevespi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-data-warehouse/22?planning-poker) with Zenhub @dleard

**Comment by mikevespi** [comment]
This network policy was created manually due to apparent Argo / Helm lookup problems. The database has been connected to Metabase, but it's 17:37 on a Friday and I don't see a schema yet. I'll let the jobs run and see if that solves it before marking complete.

**Comment by patriciarussellCAS** [comment]
@mikevespi is this complete?
