### ISSUE TITLE
As a devops specialist I want to run the cas-pipeline provisioning script on the new namespace so that it has the required basic setup

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-data-warehouse#7]
We are going to need to run the scripts out of cas-pipeline over the new namespace set.

Todo:
- [x] run `make authorize` to create the proper roles for the team in the new namespace set
- [x] run `make provision` to create the basic secrets needed for the namespace
- [x] run `make provision_artifactory` so that we have an artifactory SA and can pull images from there

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-data-warehouse/7?planning-poker) with Zenhub @andrea-williams @dleard @BCerki @JoshLarouche @Sepehr-Sobhani
