### ISSUE TITLE
As a developer I want a Crunchy DB Postgres cluster deployed to the data warehouse namespace so I can explore data ingestion solutions

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-data-warehouse#8]
We need to deploy a Postgres cluster using the Postgres Operator to the data warehouse namespace.

Todo:
- [x] Create a helm chart in the cas-data-warehouse repo
- [x] Use the minimal postgres chart from platform services (already implemented for registration)
- [x] Add a Postgres Operator template to the deployment using the PGO images from artifactory
- [ ] Postgres is running in openshift in the data warehousing namespace 
- [ ] Backups are written to GCS

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-data-warehouse/8?planning-poker) with Zenhub @andrea-williams @dleard @BCerki @JoshLarouche @Sepehr-Sobhani
