### ISSUE TITLE
Procure a new namespace set for the data warehouse deployment

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-data-warehouse#9]
Get a new tools-dev-test-prod namespace set from platform services. I think they default us to the smallest namespace size on creation and we have to prove that we need more resources. The small namespace size caused issues for the Connectivity team when deploying a Postgres cluster. We could check in with them to see how that turned out & if they were able to get their namespace upgraded.

Todo:

- [x] figure out where the namespace should be (gold or silver - or both?)
- [x] procure a namespace set from platform services

**Comment by pbastia** [comment]
Talk to Cailey about whether this should be a Silver or Gold deployment, and advice about data transfers between both
